# Use Apple's default Clang compiler
CXX = clang++

# Use modern C++20 standard and include debugging symbols
CXXFLAGS = -std=c++20 -g

# --- CORE WARNINGS ---
CXXFLAGS += -Wall -Wextra -Wpedantic

# --- BAD HABIT DETECTORS ---
CXXFLAGS += -Wshadow             # Warns if a local variable hides a global/member variable
CXXFLAGS += -Wconversion         # Warns on implicit type conversions that might lose data
CXXFLAGS += -Wsign-conversion    # Warns on mixing signed and unsigned ints
CXXFLAGS += -Wcast-align         # Warns on dangerous pointer casts
CXXFLAGS += -Wformat=2           # Strict checks for printf/scanf style formatting
CXXFLAGS += -Wnull-dereference   # Warns if a null pointer might be dereferenced
CXXFLAGS += -Wold-style-cast     # Forces C++ casts (static_cast) instead of C-style (int)x
CXXFLAGS += -Woverloaded-virtual # Warns if a derived class hides a base virtual function
CXXFLAGS += -Wnon-virtual-dtor   # Warns if a class has virtual functions but no virtual destructor

# --- THE ENFORCER ---
# Promotes ALL warnings generated by the flags above into compilation errors
CXXFLAGS += -Werror

# --- RUNTIME SANITIZERS (Optional but highly recommended) ---
# These catch memory leaks, out-of-bounds access, and undefined behavior when running
CXXFLAGS += -fsanitize=address,undefined

# Name of your final executable
TARGET = main

# Find all .cpp files in the current directory
SRCS = $(wildcard *.cpp)
# Replace the .cpp extension with .o for object files
OBJS = $(SRCS:.cpp=.o)

# Default rule when you just type 'make'
all: $(TARGET)

# Link the object files into the final executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Compile each source file into an object file
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean up build files when you type 'make clean'
clean:
	rm -f $(OBJS) $(TARGET)